version: '3.7'

services:

  app:
    container_name: docker-todo-app
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /home/node/workspace
    volumes:
      - ./:/home/node/workspace
    environment:
      MYSQL_HOST: data
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - app-network

  data:
    container_name: docker-todo-data
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - app-network

volumes:
  data-volume:

networks:
  app-network:
